#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

#define INIT_SIZE 24
#define MIN_IMAGE_TRUE 95
#define MIN_IMAGE_FALSE 42
#define VARIANCE_THREHOLD 22
#define VARIANCE_ERROR ERROR

#define ERROR -1

#define LOG

#endif // CONFIG_H_INCLUDED
